INSERT INTO public.volunteer ("id", "firstName", "lastName", "email", "createdAt", "updatedAt")
VALUES
    (uuid_generate_v4(), 'John', 'Doe', 'john.doe@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Jane', 'Smith', 'jane.smith@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Bob', 'Johnson', 'bob.johnson@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Alice', 'Williams', 'alice.williams@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Mike', 'Brown', 'mike.brown@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Sarah', 'Davis', 'sarah.davis@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'David', 'Miller', 'david.miller@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Emily', 'Wilson', 'emily.wilson@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Michael', 'Taylor', 'michael.taylor@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Olivia', 'Anderson', 'olivia.anderson@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Daniel', 'Thomas', 'daniel.thomas@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Sophia', 'Jackson', 'sophia.jackson@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Matthew', 'White', 'matthew.white@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Ava', 'Harris', 'ava.harris@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Christopher', 'Martin', 'christopher.martin@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Isabella', 'Thompson', 'isabella.thompson@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Andrew', 'Garcia', 'andrew.garcia@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Mia', 'Martinez', 'mia.martinez@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Joshua', 'Robinson', 'joshua.robinson@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Emily', 'Clark', 'emily.clark@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Alexander', 'Rodriguez', 'alexander.rodriguez@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Madison', 'Lewis', 'madison.lewis@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Ethan', 'Lee', 'ethan.lee@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Abigail', 'Walker', 'abigail.walker@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Daniel', 'Hall', 'daniel.hall@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Chloe', 'Allen', 'chloe.allen@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Henry', 'Young', 'henry.young@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Evelyn', 'Hernandez', 'evelyn.hernandez@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Michael', 'King', 'michael.king@example.com', CURRENT_DATE, CURRENT_DATE),
    (uuid_generate_v4(), 'Mia', 'Wright', 'mia.wright@example.com', CURRENT_DATE, CURRENT_DATE);

